---
- name: Create User {{ dbuser }} with access to database {{ dbname }} and privileges *.{{ dbname }}
  mysql_user: name={{ dbuser }} password={{ dbpass }} priv={{ dbname }}.*:ALL host='%' state=present login_password={{ mysql_root_password }} login_user=root