---
- block:
  - include: ubuntu.yml
    when: ansible_distribution == 'Ubuntu'
  # set up mysql variables
  - name: create MySQL configuration file
    action: template src=mysql.my.cnf.j2 dest=/etc/mysql/my.cnf
    notify: 
    - restart mysql

  - name: Start and enable service
    service: name=mysql state=started enabled=yes

  - include: mysql_secure_installation.yml
    when: mysql_root_password is defined
  become: true
  become_method: sudo
  become_user: root