---
- name: Remove MariaDB completely
  shell: sudo apt-get purge mysql-server mysql-client mysql-common mysql-server-core-5.5 mysql-client-core-5.5; sudo rm -rf /etc/mysql /var/lib/mysql; sudo apt-get autoremove; sudo apt-get autoclean
