---
- name: Add repository file
  template: src=mariadb_ubuntu.list.j2 dest=/etc/apt/sources.list.d/mariadb.list owner=root group=root mode=0644
  register: mariadb_list

- name: Add repo key
  apt_key: id=1BB943DB url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xCBCB082A1BB943DB state=present
  register: mariadb_key

- name: Update apt cache
  apt: update_cache=yes
  when: mariadb_list.changed == True or mariadb_key.changed == True

- name: Unattended package installation
  shell: export DEBIAN_FRONTEND=noninteractive
  changed_when: false

- name: Install MariaDB
  apt: pkg={{ item }} state=present
  with_items:
    - mariadb-server
    - mariadb-client
    - libmariadbclient-dev

- name: Install the mysqlclient through pip
  pip:
    name: "{{ item }}"
    state: forcereinstall
  with_items:
    - pip
    - mysqlclient

# set up mysql variables
- name: create MySQL configuration file
  action: template src=mysql.my.cnf.j2 dest=/etc/mysql/my.cnf
  notify: 
  - restart mysql

# Force restart of mysql to open ports
- name: Restarting MySQL
  service: name=mysql state=restarted