---
- name: Check whether swap is already enabled or not
  shell: cat /etc/sysctl.conf
  register: swap_enabled
  become: true
  become_method: sudo
  become_user: root

- block:
  # Note if RAM < 1G, we can not use bs=1G so therefor we use 1M http://thelinuxfaq.com/465-dd-memory-exhausted-by-input-buffer-of-size-bytes-1-0-gib
  - name: create swap file
    command: dd if=/dev/zero of=/swapfile bs=1M count={{ swap_size_in_m }} 

  - name: change permission type
    file: path=/swapfile mode=600 state=file

  - name: setup swap
    command: mkswap /swapfile

  - name: create swap
    command: swapon /swapfile

  - name: Add to fstab
    action: lineinfile dest=/etc/fstab regexp="swapfile" line="/swapfile none swap sw 0 0" state=present

  - name: start swap
    command: swapon -a

  - name: set swapiness
    sysctl:
      name: vm.swappiness
      value: "10"

  - name: set swapiness
    sysctl:
      name: vm.vfs_cache_pressure
      value: "50"

  when: swap_enabled.stdout.find('swappiness') == -1