---
- name: Install nginx
  apt: pkg=nginx state=installed

- name: Copy settings
  template: src=nginx.conf.j2
            dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: Disable default server block
  file: path=/etc/nginx/sites-enabled/default
        state=absent
  notify:
    - restart nginx