---
- hosts: all
  # become: true
  # become_user: root
  vars_files:
    - settings.yml
  vars:
    files_directory: "/vagrant/site"
  roles:
    - common
    - ssh
    - nginx
    - nginx_node
    - mariadb
    - nodejs